version: "3.7"

services:
  web-app:
    image: mcr.microsoft.com/azuredocs/aks-helloworld:v1

  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.2.1
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_REFRESH: 30m
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: GitHub
      OAUTH2_PROXY_REDIRECT_URL: http://localhost/oauth2/callback

  nginx:
    image: nginx:1.21.6-alpine
    depends_on:
      - oauth2-proxy
      - web-app
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
